import React, { useEffect , useRef} from "react";
import QrReader from 'react-qr-scanner';
import { useState } from "react";
import { Paper, Typography, CircularProgress, Divider, TextField, Button, Grid, TextareaAutosize    } from '@material-ui/core';
import Txn from "./Txn.js";
import { useDispatch, useSelector } from 'react-redux';
import { logTime } from "../../actions/attendance";
import { getTxns } from "../../actions/transactions";
/*@brief: Render QR Scanner Page
* @author: Justin To, Daniel Capinpin, Cara Alabanza, and Janielle Enrqiuez
*/
const QR = () => {
    const log = useSelector((state)=>state.log);
    const dispatch= useDispatch();
    const [status, setStatus]=useState(true);
    
    /*@brief: handling of error
    * @params: error
    * error: error found
    * @author: Justin To, Daniel Capinpin, Cara Alabanza, and Janielle Enrqiuez
    */
    const handleErrorFile = (error)=>{
        console.log(error);
    }

    /*@brief: handling of successful scan
    * @params: result
    * error: scanned result
    * @author: Justin To, Daniel Capinpin, Cara Alabanza, and Janielle Enrqiuez
    */
    const handleScanFile = (result)=>{
        if(result){
            try{
                result=JSON.parse(result.text);     //check if qr is valid and generated by our system
                console.log(result);
                if(result.userID && result.txnID && result.postID && status){
                    setStatus(false);
                    dispatch(logTime(result));
                }
            }catch(error){
                console.log(error);
            }
        }
        
        

    }
    /*@brief: set status to be true
    * @author: Justin To, Daniel Capinpin, Cara Alabanza, and Janielle Enrqiuez
    */
    const setTrue=()=>{
        setStatus(true);
        window.location.reload(false);
    }

    return(
        <>
        <Grid container alignItems="stretch" spacing={3}>
            <Typography>Scan QR Code:</Typography>
        </Grid>
        {console.log(status)}
        {!status ? (
            <>
            <Typography>Scan Again?</Typography>
            <Button onClick={setTrue}>Yes</Button>
            </>
            
        ) : null}
        <Grid container alignItems="stretch" spacing={3}>

            <QrReader
            
                delay={300}
                style={{width: '100%'}}
                onError={handleErrorFile}
                onScan={handleScanFile}
                
                
            />
            {log?(<Typography>{JSON.stringify(log)}</Typography>):null}
            
        </Grid>
        
        </>
    )
}

export default QR;